devel/libconfuse/Makefile
devel/libconfuse/distinfo
devel/libconfuse/pkg-plist

This is necessary to build https://github.com/troglobit/inadyn to resolve https://bugs.freenas.org/issues/7493

Update devel/libconfuse to 3.2.1

---

devel/libhyve-remote/Makefile
devel/libhyve-remote/distinfo

Fixes:
2017-09-20 01:27 Marcelo Araujo o - Explicit include header in /usr/local/include.
2017-09-20 01:30 Marcelo Araujo o - Revert bhyve-patch section on Makefile.
2017-09-20 01:33 Marcelo Araujo o - Don't build the examples by default.
2017-09-20 11:37 Marcelo Araujo o Explicitly add another headers path.
2017-11-30 10:48 Marcelo Araujo o [master] {origin/master} {origin/HEAD} Bind the port to an IPv4 address. If we want bind to all, we can just use 0.0.0.0.

Update libhyve-remote to 0.1.4.

---

net-mgmt/collectd5/Makefile
net-mgmt/collectd5/files/patch-src_memory.c

"Cache" memory is no longer used.  Now it is counted as "Laundry".
Ticket:	#27356

Make collectd account "Laundry" memory.

---

net/viamillipede/Makefile
net/viamillipede/distinfo

bump for v0.6 git tag
https://github.com/agokhale/viamillipede/commit/a6d798e0d6f9485d481be513683475e4c457c2aa

minimize transporter accidents

---

devel/libhyve-remote/Makefile
devel/libhyve-remote/distinfo

Changelog:
- Remove double free.
On vnc_init_server() we free already the struct server_softc *sc,
we don't need free it on bhyve/vncserver.c. This was probably the
root cause of a SIGBUS.
Ticket: #37842, #37786 and possible #34747

 - Update to 0.1.4.2.

---

net-mgmt/collectd5/Makefile
net-mgmt/collectd5/files/patch-src__zfs_arc.c

Report the actual (compressed) L2ARC size instead of the uncompressed size.
Ticket: #32793

[collectd] Fix L2ARC size reporting

---

sysutils/uefi-edk2-bhyve/Makefile
sysutils/uefi-edk2-bhyve/distinfo

Changelog:
Enable OvmfPkg/VirtioScsiDxe.
Extend _PRT tables to cover all possible PCI slots and INT lines.
Ticket: #57021

[11.2-stable] tkt-57021: - Update sysutils/uefi-edk2-bhyve to 0.2.

---

net/py-netif/Makefile
net/py-netif/distinfo

This commit updates py-netif port to reflect the latest commint in the py-netif repository.
Ticket: #58185

tkt-58185: Update py-netif port

---

net/py-netif/Makefile

This commit adds support for py-netif port to use GNU Configure when building/installing it.

Py-netif port bug fix

---

net-mgmt/collectd5/Makefile
net-mgmt/collectd5/files/patch-configure.ac
net-mgmt/collectd5/files/patch-src__Makefile.am
net-mgmt/collectd5/files/patch-src__df.c

MNT_IGNORE is a flag that indicates a filesystem should not be counted by df.
This change teaches the df plugin for collectd to obey it.
The df plugin was designed to support statfs as well as statvfs.  It preferred
statvfs for no apparent reason.  The use of statvfs seems to be discouraged by
the man page, it doesn't appear to provide any additional data over statfs,
and it does not include the `f_flags` field we need to check MNT_IGNORE.  So,
use of statvfs has been removed.  We will always use statfs.
LIBZFS-dependent code is also removed. We have not been using it, and it does not provide any additional metrics. ZFS should report the values we are interested in via statfs().
Ticket: #56607

tkt-56607: Skip mounts marked MNT_IGNORE for df

---

net-mgmt/collectd5/Makefile

collectd 5.7.2 still depends on libltdl.
Ticket: #56607

tkt-56607: [collectd] Undo breaking change to Makefile and bump revision

---

net-mgmt/collectd5/Makefile
net-mgmt/collectd5/files/patch-src__zfs_arc.c

(cherry-picked from 50e662220df053e85931587acada1b06cfe52441)
Report L2ARC size using l2_asize kstat rather than l2_size.
The uncompressed size is reported by l2_size, while the actual
(compressed) size is reported by l2_asize.
Bump port revision after updating patch
Ticket: #32793

tkt-32793: [collectd] Fix L2ARC size reporting

---

net-mgmt/collectd5/Makefile
net-mgmt/collectd5/files/patch-src__ctl.c

Previous API consumed too much memory, but also appeared to be broken
after FreeBSD 11.2 merge.
Ticket:	#63402
(cherry picked from commit 51eca18e09220459a27f9eddaf3297dd19d8f52c)

tkt-63402: Switch collectd ctl plugin to new CTL statistics API.

---

net/samba49/files/0001-Freenas-master-mdns-fixes-22.patch
net/samba49/files/0001-add-parameters-for-ha-configuration.patch

Add two new parameters to samba:
"zeroconf name = <string>" - this can be used to set the name to the virtual hostname of the server rather than merely defaulting to the hostname.
"truenas backup controller = <yes|no>"  - this parameter lets us bail out of registering on the passive controller. In the future this will be used to stop other things that we don't want samba to do on a passive controller.

tkt-39867: Make mdns name configurable and add some HA handling

---

net/samba49/files/0001-zfs-provisioning-patches.patch

- Differentiate between ACLS on files and directories. Samba was checking for CI|OI on files, but those inheritance bits are invalid. This probably works outside of ZFS because the ACL is stored in an xattr. This changes behavior so that we strip the inheritance bits from the ACL for files.
- On a freshly provisioned server, the GPO entries may lack nTSecurityDescriptor message in the GPO information. Add some handling for this edge case.

tkt-67125: Fix various ACL checks in samba DC code

---

net/samba49/files/0001-zfs-provisioning-patches.patch

sysvol acl reset during domain provisioning can fail due to
fset_nt_acl failing with NT_STATUS_INVALID_PARAMETER. This is
because samba defaults to setting the acl_xattr vfs object for
domain controllers unless it is explicitly overriden. During
provisioning there is not a reliable mechanism to ensure that
we are overriding the default with zfsacl. Instead, check for
nfs4 ACL support on samba's statedir (the default location for
the sysvol share), and enable zfsacl accordingly.

tkt-71849: Automatically enable zfsacl if sysvol supports nfs4 acls.

---

net/samba49/Makefile
net/samba49/files/0001-add-parameters-for-ha-configuration.patch
net/samba49/files/samba_server.in
sysutils/py-wsdd/Makefile
sysutils/py-wsdd/distinfo
sysutils/py-wsdd/pkg-descr

- Currently defaults to off
- Can be enabled by setting "enable web service discovery = Yes" as a global smb4.conf parameter if py-wsdd port is installed.
- Also add ability to disable the netbios name server (nmbd), and permissions check / fix for "/var/db/samba4/winbindd_privileged" during samba_server commands (There are an increasing number of occurrences of freenas users breaking these permissions; thus additional safety net is needed).

tkt-72099: Add support for WS-Discovery to samba port

---

net/samba49/files/patch-source3__modules__vfs_recycle.c

When the ZFS aclmode property is set to "restricted" on a dataset
and extended ACL entries exist on a file, then chmod() is denied.
This breaks user expectations because samba fails to set the posix
mode of the recycle repository. So we need to strip extended ACL
entries when we create the initial ".recycle" directory, and
thereby allow vfs_recycle to work as intended. (.recycle permissions
controlled by "recycle:directory_mode = MODE" and subdirectory
permissions controlled by "recycle:subdir_mode = MODE".
Allow restoring intial behavior by adding parameter:
recycle:preserveacl=Yes

tkt-73891: Fix permissions on recycle bin in samba

---

net/samba49/files/0001-zfs-provisioning-patches.patch

sysvol acl reset during domain provisioning can fail due to
fset_nt_acl failing with NT_STATUS_INVALID_PARAMETER. This is
because samba defaults to setting the acl_xattr vfs object for
domain controllers unless it is explicitly overriden. During
provisioning there is not a reliable mechanism to ensure that
we are overriding the default with zfsacl. Instead, check for
nfs4 ACL support on samba's statedir (the default location for
the sysvol share), and enable zfsacl accordingly.

tkt-72011: Automatically enable zfsacl if sysvol supports nfs4 acls. (by anodos325)

---

net/samba49/Makefile
net/samba49/files/0001-add-parameters-for-ha-configuration.patch
net/samba49/files/samba_server.in
sysutils/py-wsdd/Makefile
sysutils/py-wsdd/distinfo
sysutils/py-wsdd/pkg-descr

- Currently defaults to off
- Can be enabled by setting "enable web service discovery = Yes" as a global smb4.conf parameter if py-wsdd port is installed.
- Also add ability to disable the netbios name server (nmbd), and permissions check / fix for "/var/db/samba4/winbindd_privileged" during samba_server commands (There are an increasing number of occurrences of freenas users breaking these permissions; thus additional safety net is needed).

tkt-74190: Add support for WS-Discovery to samba port (by anodos325)

---

net/samba49/files/patch-source3__modules__vfs_recycle.c

When the ZFS aclmode property is set to "restricted" on a dataset
and extended ACL entries exist on a file, then chmod() is denied.
This breaks user expectations because samba fails to set the posix
mode of the recycle repository. So we need to strip extended ACL
entries when we create the initial ".recycle" directory, and
thereby allow vfs_recycle to work as intended. (.recycle permissions
controlled by "recycle:directory_mode = MODE" and subdirectory
permissions controlled by "recycle:subdir_mode = MODE".
Allow restoring intial behavior by adding parameter:
recycle:preserveacl=Yes

tkt-74262: Fix permissions on recycle bin in samba (by anodos325)

---

net/samba49/files/patch-source3__modules__vfs_zfsacl.c

This appears to primarily affect users who have enabled "Unix" permissions type for SMB shares because chmod 0700 leaves the owner dD bits unset. Although this is technically an unsupported configuration, it's better to not diverge from upstream samba in zfsacl and contain work on improving ACL check / compatibility inside ixnas.

tkt-75685: Fix regression introduced by fix for sysvol ACL check in initial 4.9 work

---

net/samba49/files/patch-source3__modules__vfs_zfsacl.c

This appears to primarily affect users who have enabled "Unix" permissions type for SMB shares because chmod 0700 leaves the owner dD bits unset. Although this is technically an unsupported configuration, it's better to not diverge from upstream samba in zfsacl and contain work on improving ACL check / compatibility inside ixnas.

tkt-75892: Fix regression introduced by fix for sysvol ACL check in initial 4.9 work (by anodos325)

---

net/samba49/Makefile
net/samba49/files/0001-fix-builtin-guests-ldap.patch

If create_builtin_guests() fails with NT_STATUS_ACCESS_DENIED (i.e. no write access to the remote LDAP server), then add BUILTIN\guests directly to token.

tkt-77629: Fix guest account intialization in readonly LDAP environments (by anodos325)

---

converters/convmv/Makefile
converters/convmv/distinfo

(cherry-picked 5f17486ff9e185c77519be330b815243a8ee236d)
Ticket: https://redmine.ixsystems.com/issues/78141

[converters/convmv] Sync port to upstream version (2.05)

---

net/samba410/Makefile
net/samba410/files/0001-enable-keytab-updates-on-machine-account-change.patch

When kerberos method was set to 'secrets and keytab', the two would get out of sync.
New behavior is to regenerate the machine account principals in system keytab on machine account
password change.

tkt-101379: Add support for updating system keytab on machine account pwd change

---

sysutils/sedutil/Makefile
sysutils/sedutil/distinfo

This improves FreeBSD compatibility and fixes few minor bugs in main code.
Also it adds initial support for newer Opalite and Pyrite SSC, which devices
are already found on market.

Update port to include my new sedutil patches.

---

sysutils/sedutil/Makefile
sysutils/sedutil/distinfo

While being there I've also added initial support for Opalite and Pyrite SSC specifications, found in some devices.

NAS-101427: Improve sedutil FreeBSD support / 11.2

---

sysutils/tw_cli/Makefile
sysutils/tw_cli/files/407.status-3ware-raid.in

This commit fixes a bug where we sent alerts when we had blank lines. The following cases have been covered:
1) If the old alarm file had some entries and the new one is empty or filled with whitespace, we donot send an alert for new alarms.
2) If the new alarm file is empty but the old alarm file has some alerts, we donot send an alert.
3) If the new alarm file does not have any additions of any alarm and is similar to the old alarm file or perhaps has only added blank lines, we donot send an alert.
Ticket: #NAS-101788

NAS-101788 / 11.2 / Don't send empty alerts

---

sysutils/asigrajail/Makefile
sysutils/asigrajail/distinfo
sysutils/asigrajail/pkg-descr

This commit adds asigra jail image port which we will use for having asigra plugin image builtin in the TN iso.

NAS-102252 / 11.3 / Add asigra jail image port

---

devel/libvirt/Makefile

This commit fixes a bug where zfs binary couldn't be detected by libvirt port.

NAS-100417 / 12 / Bug fix for libvirt port

---

sysutils/iocage/Makefile

This commit updates git dependency in iocage as 2.1.10 version is not available in 11.2.

Update iocage git dependency

---

devel/libvirt/Makefile
devel/libvirt/files/patch-src_bhyve_bhyve__command.c

This PR introduces following fixes:
1) Where libvirt did not respect the value of PCI slot function for bhyve driver.
2) Add VNC authentication support
3) Allow libvirt to specify sectorsizes for disks

NAS-100417 / 12 / Bug fixes for libvirt ( bhyve driver )

---

devel/libvirt/Makefile
devel/libvirt/files/libvirtd.in

This commit adds changes to ensure that we don't stop libvirt via rc framework when a system shutdown is initiated and instead make sure that middlewared takes responsibility for this.

NAS-100109 / 12 / Don't stop libvirt via rc framework on shutdown

---

net/samba49/files/0001-add-ix-custom-vfs-modules.patch

Fix simple oversight that users may want to set both of these
parameters on the same share.

NAS-103422 / 11.2 / Fix ordering of adding userspace quota and home datasets in ixnas

---

net/samba410/files/0001-add-ix-custom-vfs-modules.patch

Some users have requested being able to set both of these parameters
on the same share.
Minor code cleanups.

NAS-103422 / 11.3 / fix ordering of dataset creation and adding userspace quotas in ixnas

---

net/samba410/files/0001-add-ix-custom-vfs-modules.patch

Samba change to avoid user confusion if they insist on not using
ACLs.

NAS-103456 / 11.3 / Automatically set zfs_acl_map_modify=True if connectpath ACL is trivial

---

benchmarks/fio/Makefile

Since fio 3.6 people packaging fio(such as ports) have been instructed to disable native optimizations. This fixes that the freenas nightlies fio is broken on c3000 atoms among other platforms. 
https://github.com/axboe/fio/commit/a817dc3b3b5a0efc95aaca366875eac67607cd5b

NAS-103609 / 11.3 / #HQ-176 Disable native optimizations for fio

---

benchmarks/fio/Makefile

Since fio 3.6 people packaging fio(such as ports) have been instructed to disable native optimizations. This fixes that the freenas nightlies fio is broken on c3000 atoms among other platforms.
axboe/fio@a817dc3
This commit also reverts previous attempt at this patch and pulls in upstream ports fix

NAS-103609 / 11.3 / Nas-103609 / 11 / Disable native optimizations for fio

---

devel/Makefile
devel/py-remote-pdb/Makefile
devel/py-remote-pdb/distinfo
devel/py-remote-pdb/pkg-descr

No extras, proper handling around connection failures and CI. Based on pdbx.
WWW: https://github.com/ionelmc/python-remote-pdb

NAS-103742 / 11.3 / devel/py-remote-pdb: Remote vanilla PDB (over TCP sockets) done right

---

net/samba410/files/0001-add-shadow_copy_zfs.patch

Add non-default tdb-based caching backend for shadow_copy_zfs.
(new parameter shadow:cache_backend = {'memcache', 'tdb'})
TDB backend is experimental, but may scale better in large environments (more testing needed).
Cleanups (fix mixtures of tabs and spaces, whitespace fixes).
Remove some unnecessary TALLOC_FREE() calls.

NAS-103734 / 11.3 / Code cleanups in shadow_copy_zfs and add tdb-based cache

---

net/samba410/files/0001-add-ix-custom-vfs-modules.patch

Remove unnecessary calls to acl_get_file() and acl_get_fd().
Calculate SD based on POSIX mode since ACL is trivail. Move
check for lp_dos_filemode to [f]get_nt_acl processing to make this
feature work correctly. Access check for SEC_FILE_WRITE_ATTRIBUTE
occurs before [f]get_dos_attributes is called, and so the mapping
has to happen here.

NAS-103778 / 11.3 / Add [f]get_nt_acl functions to vfs_noacl

---

net/samba410/files/0001-add-ix-custom-vfs-modules.patch
net/samba410/files/0001-add-shadow_copy_zfs.patch
net/samba410/files/patch-source3__modules__wscript_build

Simplify snapshot related code in smblibzfs. Convert to using
linked list of snapshots. Reduce instances of iterating through
snapshot lists in shadow_copy_zfs. Lay groundwork for future
VFS modules that interact with libzfs. Add ability to specify
start and end times for snapshot queries.

Add functions to take, delete, and rollback snapshots to smblibzfs

---

net/samba410/Makefile
net/samba410/files/experimental_aio.patch
net/samba410/files/wscript_changes.patch

Add two new experimental AIO modules that are not exposed to end-users.
aio_spthread creates a dedicated pthreadpool for AIO reads and writes
aio_fbsd uses kevent, kqueue, and POSIX AIO for AIO reads and writes

Add two new experimental AIO modules

---

sysutils/iocage/Makefile

This commit adds rcs57 as a dependency for iocage as merge(1) is required for jail upgrades. ( https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240177 )

NAS-104559 / 11.3 / Add devel/rcs57 as a dependency for iocage

---

net/samba410/Makefile
net/samba410/files/ix-smbtorture.patch

Basic tests to verify that we are properly enumerating
snapshots and allowing access over the SMB protocol.

NAS-104567 / 11.3 / Add regression tests for shadow_copy_zfs to smbtorture

---

net/samba410/Makefile
net/samba410/files/debug.patch

Open the log directory on debug initialization and use
openat() calls relative to this log dir fd for later log file
re-initialization.

NAS-105130 / 11.3 / Use openat() in Samba debug logs

---

net/samba410/files/0001-add-ix-custom-vfs-modules.patch

Add special handling for robocopy behavior of sending 01/01/1980
mtime (other times not set) before setting the file time. This is
to prevent FreeBSD from setting the file create time to 01/01/1980.

NAS-105257 / 11.3 / Fix regression in vfs_ntimes

---

net/samba410/files/0001-add-ix-custom-vfs-modules.patch

Only work around special robocopy timestamp. Allow mtime to be set
even if it will result in unexpected changes to the btime. This reduces
POLA violation for users (still doesn't eliminate) and fixes reported issues
with some 3rd party backup software.

NAS-105288 / 11.3 / Make ntimes function in vfs_ixnas more permissive

---

devel/libvirt/Makefile
devel/libvirt/files/patch-src_bhyve_bhyve__command.c

Windows vm's only like to use 0/31 slots for lpc and otherwise they don't work as desired wrt keyboard. -P flag has been removed as well to keep consistent with 11.3 behaviour.

Patch libvirt to use 31st slot for lpc 
