freenas/ports

net-mgmt/collectd5/files/patch-src__zfs_arc.c

Port https://github.com/collectd/collectd/commit/42c95164f7c6bcc5fe831c3d9844aca0e69faf4d to this branch.

Fix ZFS Arc hit ratio statistics

---

net/rclone/Makefile
net/rclone/distinfo
www/py-azure-common/Makefile
www/py-azure-common/distinfo
www/py-azure-common/pkg-descr
www/py-azure-storage/Makefile
www/py-azure-storage/distinfo
www/py-azure-storage/pkg-descr

Add support for CloudSync Azure backups

---

security/pam_mkhomedir/Makefile
security/pam_mkhomedir/files/patch-pam_mkhomedir.c

Fix of commits getting lost. Should bring back fixes for #12864 and #23603

Pull in pam_mkhomedir patches bugs 12864/23603

---

sysutils/grub2-efi/Makefile
sysutils/grub2-pcbsd/Makefile

Remove GCC depend for grub2-pcbsd and grub2-efi

---

dns/py-bonjour/files/patch-pybonjour.py

Fix py-bonjour port

---

sysutils/consul-alerts/Makefile
sysutils/consul-alerts/distinfo
sysutils/consul-alerts/files/consul-alerts.in

- Update aws-sdk-go:v1.12.45 and bump PORTREVISION. 
Ticket: #25037

 Set AWS env variables for config and creds. 

---

sysutils/py3-iocage/Makefile

Removes unused deps and adds the new required one.
Ticket: ##27253
(cherry picked from commit d63dd98350721dfa3da744de7ee9bcca3e518569)

Update iocage makefile

---

sysutils/grub2-pcbsd/Makefile
sysutils/grub2-pcbsd/files/00_header.in

Use `vt` for BIOS as well

---

sysutils/libsunacl/Makefile
sysutils/libsunacl/distinfo

(cherry picked from commit 8e9166af1590c21ab5882daffead97cac28f0154)
Signed-off-by: Timur I. Bakeyev <timur@iXsystems.com>

Update port to version 1.0.1, change maintainer and download site.

---

net/samba47/Makefile

Bump port revision, specify required version of libsunacl.

Bump port revision for zfsacl patch

---

net/viamillipede/Makefile

fix CATEGORIES after CI failure
https://builds.ixsystems.com/jenkins/job/FreeNAS%20-%20Build%20Pipeline/job/PR-29/1/console

  fix CATAGORIES, after copypasta error

---

sysutils/consul/files/consul.in

Tag consul syslog messages

---

security/Makefile
security/py-asyncssh/Makefile
security/py-asyncssh/distinfo
security/py-asyncssh/pkg-descr

I still need to add one modification - I've pushed this code to discuss some changes.
Ticket: #25945

Asyncssh python lib port

---

sysutils/sedutil/Makefile
sysutils/sedutil/distinfo

Update sedutil to 1.15.1 and new FreeBSD.

---

security/sssd/files/patch-src__sss_client__pam_sss.c

Use correct pam constants

---

www/minio/files/minio.in

Make minio config directory permissions happier

---

net/netatalk3/files/netatalk.in

Require dbus to be running before netatalk

---

security/sssd/Makefile

Bump sssd port revision

---

net/netatalk3/Makefile

Add p5-IO-Socket-INET6 as a run dependency

---

security/sssd/files/patch-src__sss_client__pam_sss.c

Make sure pam_sss is quiet when told to be quiet

---

security/sssd/Makefile

Bump port revision

---

net-mgmt/netdata/files/patch-conf.d__health.d__ram.conf

Don't count arc against available ram on FreeBSD

---

sysutils/dsoperator/files/DSOP.jnlp.template

DSOP.jnlp -> DSOP.jnlp.template

---

devel/Makefile
devel/py-bhyve/Makefile
devel/py-bhyve/distinfo
devel/py-bhyve/pkg-descr

This commit adds a new port for py-bhyve module which is a python wrapper around freebsd's libvmmapi.
Ticket: #41228

Port for py-bhyve module

---

devel/py-libzfs/Makefile
devel/py-libzfs/distinfo

tkt-58371: Fix build with older cython

---

devel/py-libzfs/Makefile

tkt-58371: Use configure in py-libzfs

---

net-mgmt/collectd5/Makefile
net-mgmt/collectd5/files/patch-configure.ac
net-mgmt/collectd5/files/patch-src__Makefile.am
net-mgmt/collectd5/files/patch-src__df.c

(merged from freenas/master branch)
Ticket: #56607

tkt-56607: [collectd] Prune libzfs code, add MNT_IGNORE support to df plugin

---

net-mgmt/netdata/Makefile
net-mgmt/netdata/distinfo
net-mgmt/netdata/files/patch-conf.d__health.d__ram.conf
net-mgmt/netdata/files/patch-configure.ac
net-mgmt/netdata/files/patch-src_common.c
net-mgmt/netdata/files/patch-src_freebsd__sysctl.c
net-mgmt/netdata/pkg-plist

Revert "Update Netdata port"

---

net-mgmt/collectd5/files/patch-src__rrdcached.c

…lures as warnings (as rrdtool plugin does)

tkt-72235: fix(net-mgmt/collectd5): Make rrdcached plugin report rrdc_update fai… (by themylogin)

---

net/samba49/files/0001-add-ix-custom-vfs-modules.patch

- Fix to pass base.dir2 smbtorture test
- Remove configuration options for get | set dosmode functions.

tkt-73216: Improve dosmode handling in ixnas module

---

net/samba49/Makefile
net/samba49/files/0001-add-ix-custom-vfs-modules.patch

remove dependency on libsunacl for get/set nt acl

tkt-74811: Improve ACL handling in vfs_ixnas in samba

---

net/samba49/files/0001-add-ix-custom-vfs-modules.patch

- Fix to pass base.dir2 smbtorture test
- Remove configuration options for get | set dosmode functions.

tkt-74217: Improve dosmode handling in ixnas module (by anodos325)

---

net/samba49/Makefile
net/samba49/files/0001-add-shadow_copy_zfs.patch
net/samba49/files/patch-source3__modules__wscript_build
net/samba49/pkg-plist

Some key improvements:
1) support for nested ZFS datasets.
2) cached mappings for @GMT-token/name to realpath for improved performance.

tkt-21333: Add shadow_copy_zfs vfs module

---

net/samba49/Makefile
net/samba49/files/0001-add-shadow_copy_zfs.patch
net/samba49/files/patch-source3__modules__wscript_build
net/samba49/pkg-plist

Some key improvements:
1) support for nested ZFS datasets.
2) cached mappings for @GMT-token/name to realpath for improved performance.

tkt-75873: Add shadow_copy_zfs vfs module (by anodos325)

---

net/samba49/files/patch-source3__modules__vfs_zfsacl.c

(cherry picked from commit d078f4b4d615d0fa7377ee6b47ca3746d67a421b)

tkt-75892: Fix regression introduced by fix for sysvol ACL check

---

freenas/freenas/Makefile
freenas/py-middlewared/Makefile

This commit removes pandas/sssd dependency in FN 12.

Remove pandas/sssd dependency

---

freenas/freenas/Makefile

This commit adds p7zip port to freenas.
Ticket: #79815

Add p7zip port to FreeNAS

---

converters/convmv/Makefile
converters/convmv/distinfo

(cherry-picked 5f17486)
Ticket: https://redmine.ixsystems.com/issues/78141

[converters/convmv] Sync port to upstream version (2.05)

---

ftp/proftpd/Makefile
ftp/proftpd/files/patch-contrib__mod_tls.c
ftp/proftpd/files/patch-src__data.c

… proftpd/proftpd@e9f057dfc6b50f79ed817a4e45eb5c23684a4439

tkt-84755: backport proftpd/proftpd@00e1d6c18cfd3f042ead5402c0847bd932d98e4e and… (by themylogin)

---

ftp/proftpd/Makefile
ftp/proftpd/files/patch-contrib__mod_tls.c
ftp/proftpd/files/patch-src__data.c

… proftpd/proftpd@e9f057dfc6b50f79ed817a4e45eb5c23684a4439

tkt-84748: backport proftpd/proftpd@00e1d6c18cfd3f042ead5402c0847bd932d98e4e and… (by themylogin)

---

freenas/py-middlewared/Makefile

This commit adds pyotp and oath-toolkit dependencies for middlewared for 2FA support.
Ticket: NAS-100123

NAS-100123 / 12 / Add 2FA dependencies

---

sysutils/dssystem/Makefile
sysutils/dssystem/files/dssystem.in

NAS-101511 / 11.3 / sysutils/dssystem: add default dssystem_enable

---

sysutils/dssystem/Makefile
sysutils/dssystem/files/dssystem.in

NAS-101511 / 11.1 / sysutils/dssystem: add default dssystem_enable (by william-gr)

---

www/py-ws4py/Makefile
www/py-ws4py/distinfo
www/py-ws4py/files/patch-ws4py_client_____init____.py
www/py-ws4py/files/patch-ws4py_streaming.py
www/py-ws4py/files/patch-ws4py_utf8validator.py

This PR introduces following changes to ws4py port:
1) Update to latest version
2) Use github for fetching the port
3) Improve how bytes objects are validated in the utf8validator by using builtin python decode method giving us an enormous speed gain for huge objects.
Ticket: NAS-101325

NAS-101325 / 11.3 / Update ws4py Port

---

www/py-ws4py/Makefile
www/py-ws4py/distinfo
www/py-ws4py/files/patch-ws4py_client_____init____.py
www/py-ws4py/files/patch-ws4py_streaming.py
www/py-ws4py/files/patch-ws4py_utf8validator.py

This PR introduces following changes to ws4py port:
1) Update to latest version
2) Use github for fetching the port
3) Improve how bytes objects are validated in the utf8validator by using builtin python decode method giving us an enormous speed gain for huge objects.
Ticket: NAS-101325

NAS-101325 / 12 / Update ws4py Port

---

sysutils/dssystem/Makefile
sysutils/dssystem/files/dssystem.in

NAS-101511 / 11.2 / sysutils/dssystem: add default dssystem_enable (by william-gr)

---

devel/py-sysctl/Makefile
devel/py-sysctl/distinfo

This commit updates py-sysctl port.

NAS-101853 / 11.3 / Update py-sysctl Port

---

devel/py-sysctl/Makefile
devel/py-sysctl/distinfo

This commit updates py-sysctl port.

NAS-101853 / 12 / Update py-sysctl Port

---

net/samba410/Makefile
net/samba410/files/0001-add_ws_discovery.patch
net/samba410/pkg-plist

Add wsdd.py to samba scripts and modify wscript_build accordingly.

NAS-100870 / 11.3 / Add web service discovery support to Samba

---

net/mDNSResponder/Makefile

Spelling error and tabs vs spaces

NAS-101513 / 11.3 / Fix reinplace command in mDNSResponder Makefile

---

net/samba410/files/0001-add-ix-custom-vfs-modules.patch

generate parent dataset if needed, inherit aclmode, and properly inherit acl from parent dataset.

NAS-102596 / 11.3 / Fix various issues with ixnas auto_home_dataset

---

net/samba410/files/patch-source3__modules__vfs_recycle.c

Create recycle repository path on share connect if it doesn't already exist, and set mode to what is specified by the 'recycle:directory_mode' parameter. This is to resolve issues where the repository path may contain multiple components.

NAS-102634 / 11.3 / properly set permissions on recycle repositories containing macros

---

sysutils/dsoperator/Makefile
sysutils/dsoperator/files/patch-DSOP.jnlp
sysutils/dsoperator/files/patch-DSOP.jsp

This commit updates asigra port to reflect latest asigra changes.

NAS-102693 / 11.2 / Update Asigra port

---

net/nss-pam-ldapd-sasl/Makefile
net/nss-pam-ldapd/Makefile
net/nss-pam-ldapd/files/patch-nslcd.h
net/nss-pam-ldapd/files/patch-nslcd__Makefile.in
net/nss-pam-ldapd/files/patch-nslcd__config.c
net/nss-pam-ldapd/files/patch-nslcd__myldap.c
net/nss-pam-ldapd/files/patch-nslcd__myldap.h
net/nss-pam-ldapd/files/patch-nslcd__nslcd.c
net/nss-pam-ldapd/files/patch-nslcd__nslcd_json.c
net/nss-pam-ldapd/files/patch-nslcd__nslcd_json.h

On SIGUSR2 write value of lastfail and firstfail for each LDAP URI into /var/log/messages.
When receive message NSLCD_ACTION_STATE_GET reply with same information on nslcd socket.

NAS-102904 / 11.3 / Add NSLCD_ACTION_STATE_GET to nslcd

---

net/samba49/files/patch-source3__modules__vfs_recycle.c

Create recycle repository path on share connect if it doesn't already exist, and set mode to what is specified by the 'recycle:directory_mode' parameter. This is to resolve issues where the repository path may contain multiple components.

NAS-102634 / 11.2 / properly set permissions on recycle repositories containing macros (by anodos325)

---

net/avahi-app/files/patch-avahi-daemon_static-services.c
net/avahi-app/files/patch-initscript_freebsd_avahi-daemon.sh.in

add interface index support to static service config in avahi
add reload command to rc script

Add a few minor avahi improvements

---

net/samba411/files/0001-add-ix-custom-vfs-modules.patch

LibZFS changed and so must we.

Fix usage of zfs_iter_snapshots in smblibzfs

---

lang/python37/Makefile
lang/python37/Makefile.version
lang/python37/files/reentrancy_updates.patch

Use reentrant versions of getpwnam, getgrnam, getpwuid, getgrgid.
cherry-picked from:
23e65b25557f957af840cf8fe68e80659ce28629
28658485a54ad5f9df52ecc12d9046269f1654ec
e359bc24b1f3a6ce311b9ef3043d1fdf5f1bf1cd
34c7f0c04e2b4e715b2c3df1875af8939fbe7d0b

NAS-104384 / 11.3 / Cherry-pick upstream patches for reentrancy in grpmodule and pwdmodule

---

sysutils/scanlnk/Makefile
sysutils/scanlnk/distinfo
sysutils/scanlnk/pkg-descr

Source here: https://github.com/anodos325/scanlnk

NAS-104436 / 11.3 / Add simple tool to scan for symlinks back to /

---

sysutils/scanlnk/Makefile
sysutils/scanlnk/distinfo
sysutils/scanlnk/pkg-descr

Source here: https://github.com/anodos325/scanlnk

NAS-104436 / 11.2 / Add simple tool to scan for symlinks back to / (by anodos325)

---

net-mgmt/collectd5/Makefile
net-mgmt/collectd5/files/patch-src__rrdcached.c

Automatic cherry-pick failed. Please resolve conflicts by running:
git reset --hard HEAD~1
git cherry-pick -x 32b6b9f3659dde1b3e645ee376f06eadf8e682c5

NAS-104580 / 11.2 / Fix collectd spam when rrdcached is down (by themylogin)

---

net/samba49/files/0001-add-ix-custom-vfs-modules.patch

Adds ability to calculate NT ACL from POSIX mode.

NAS-104710 / 11.2 / Update vfs_noacl to latest version from 11.3-stable

---

net-mgmt/collectd5/Makefile
net-mgmt/collectd5/files/patch-src__nfsstat.c

Automatic cherry-pick failed. Please resolve conflicts by running:
git reset --hard HEAD~1
git cherry-pick -x cd2b5e51c4ff1e4663bb09cea43ca369e1261c9b
…ver stat

NAS-105313 / 12.0 / Make collectd plugin report not only NFS client stat but also NFS ser… (by themylogin)
